apiVersion: v1
kind: Template
metadata:
  name: testcase-01
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "testcase-01"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: testcase-01/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
          - name: API_BASE_SYSTEM_NAME
            value: ${API_BASE_SYSTEM_NAME}
          - name: PRIVATE_BASE_URL
            value: ${PRIVATE_BASE_URL}
          - name: PRODUCTION_PUBLIC_BASE_URL
            value: ${PRODUCTION_PUBLIC_BASE_URL}
          - name: STAGING_PUBLIC_BASE_URL
            value: ${STAGING_PUBLIC_BASE_URL}
         


parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: rh-dev
- name: TARGET_INSTANCE
  value: instance_a
- name: GIT_REPO
  value: https://github.com/redhatHameed/API-Lifecycle-Mockup.git
- name: API_BASE_SYSTEM_NAME
  value: 3scalefuse
- name: PRIVATE_BASE_URL
  value: http://maingateway-service-ah-dev.app.middleware.ocp.cloud.lab.eng.bos.redhat.com  
- name: PRODUCTION_PUBLIC_BASE_URL
  value: http://3scalefuse.app.middleware.ocp.cloud.lab.eng.bos.redhat.com  
- name: STAGING_PUBLIC_BASE_URL
  value: http://3scalefuse-staging.app.middleware.ocp.cloud.lab.eng.bos.redhat.com

